- alias: 'Restart water tank and water well boards when homeassistant starts'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: mqtt.publish
      data:
        topic: "water-well/restart"
        payload: on
    - service: mqtt.publish
      data:
        topic: "water-tank/restart"
        payload: on

- alias: 'Switch water tank intent off when water level is 95% or higher'
  trigger:
    platform: numeric_state
    entity_id: sensor.water_percentage
    above: 95
  action:
    service: switch.turn_off
    entity_id: switch.water_tank_intent

- alias: 'Switch water tank intent off when water tank goes offline'
  trigger:
    platform: state
    entity_id: binary_sensor.water_tank_availability
    to: 'unavailable'
  action:
    service: switch.turn_off
    entity_id: switch.water_tank_intent

- alias: 'Switch water tank intent on when water tank is online and the level is 40% or less'
  trigger:
    - platform: state
      entity_id: binary_sensor.water_tank_availability
      to: 'on'
    - platform: state
      entity_id: input_boolean.holiday_mode
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.water_percentage
        below: 41
  action:
    service: switch.turn_on
    entity_id: switch.water_tank_intent

- alias: 'Switch water tank intent off when holiday mode is on and when water tank is online and the level is 40% or less'
  trigger:
    - platform: state
      entity_id: binary_sensor.water_tank_availability
      to: 'on'
    - platform: state
      entity_id: input_boolean.holiday_mode
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.water_percentage
        below: 41
  action:
    service: switch.turn_off
    entity_id: switch.water_tank_intent

- alias: 'Send water well recovery time'
  trigger:
    platform: state
    entity_id: input_select.water_well_recover_time
  action:
    service: mqtt.publish
    data:
      topic: "water-well/recovery-time"
      payload_template: "{{ states('input_select.water_well_recover_time') }}"

- alias: 'Send water well recovery time when water pump becomes available'
  trigger:
    platform: state
    entity_id: binary_sensor.water_pump_availability
    to: 'on'
  action:
    service: mqtt.publish
    data:
      topic: "water-well/recovery-time"
      payload_template: "{{ states('input_select.water_well_recover_time') }}"

- alias: 'Send water tank sensor reading interval for when the water pump is off'
  trigger:
    platform: state
    entity_id: input_select.water_tank_level_sensor_interval_not_pumping
  action:
    service: mqtt.publish
    data:
      topic: "water-tank/interval-not-pumping"
      payload_template: "{{ states('input_select.water_tank_level_sensor_interval_not_pumping') }}"

- alias: 'Send water tank sensor reading interval for when the water pump is off just when the water tank becomes available'
  trigger:
    platform: state
    entity_id: binary_sensor.water_tank_availability
    to: 'on'
  action:
    service: mqtt.publish
    data:
      topic: "water-tank/interval-not-pumping"
      payload_template: "{{ states('input_select.water_tank_level_sensor_interval_not_pumping') }}"

# - alias: 'Send telegram alert when water level bellow 10%'
#   trigger:
#     platform: numeric_state
#     entity_id: sensor.water_percentage
#     below: 10
#   action:
#     service: switch.turn_off
#     entity_id: switch.water_tank_intent