- alias: 'Restart water tank and water well boards when homeassistant starts'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: mqtt.publish
      data:
        topic: "water-well/restart"
        payload: on
    - service: mqtt.publish
      data:
        topic: "water-tank/restart"
        payload: on

- alias: 'Switch water tank intent off when water tank goes offline'
  trigger:
    platform: state
    entity_id: binary_sensor.water_tank_availability
    to: 'unavailable'
  action:
    service: switch.turn_off
    entity_id: switch.water_tank_intent
    
- alias: 'Switch water tank intent off when water pump goes offline'
  trigger:
    platform: state
    entity_id: binary_sensor.water_pump_availability
    to: 'unavailable'
  action:
    service: switch.turn_off
    entity_id: switch.water_tank_intent

## Frost protection! - bellow 2 degrees
- alias: 'Switch water tank intent off when water well temperature is bellow 2'
  trigger:
    platform: numeric_state
    entity_id: sensor.water_well_temperature
    below: 2
  action:
    service: switch.turn_off
    entity_id: switch.water_tank_intent
    
# Turn the tank intent off when level to high, no matter what (don't care about holiday_mode or anything else)
- alias: 'Switch water tank intent off when water level is 95% or higher'
  trigger:
    platform: numeric_state
    entity_id: sensor.water_percentage
    above: 95
  action:
    service: switch.turn_off
    entity_id: switch.water_tank_intent
    
- alias: 'Switch water tank intent off when water well temperature falls bellow 2 degrees'
  trigger:
    platform: numeric_state
    entity_id: sensor.water_well_temperature
    below: 2
  action:
    service: switch.turn_off
    entity_id: switch.water_tank_intent

## When temperature is bellow 10 degrees start pump at 81% (Keep it as full as possible! in preparation for freezing!)
- alias: 'Switch water tank intent on when water tank is online, (the level is 40% or less) and the holiday mode if off and well temperature is above 2'
  trigger:
    - platform: state
      entity_id: binary_sensor.water_pump_availability
      to: 'on'
    - platform: state
      entity_id: binary_sensor.water_tank_availability
      to: 'on'
    - platform: state
      entity_id: input_boolean.holiday_mode
      to: 'off'
    - platform: numeric_state
      entity_id: sensor.water_percentage
      below: 81
    - platform: numeric_state
      entity_id: sensor.water_well_temperature
      below: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.water_pump_availability
        state: 'on'
      - condition: state
        entity_id: binary_sensor.water_tank_availability
        state: 'on'
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.water_percentage
        below: 81
      - condition: numeric_state
        entity_id: sensor.water_well_temperature
        below: 10
  action:
    service: switch.turn_on
    entity_id: switch.water_tank_intent

## When temperature is above 10 degrees start pump at 41%
- alias: 'Switch water tank intent on when water tank is online, (the level is 40% or less) and the holiday mode if off and well temperature is above 2'
  trigger:
    - platform: state
      entity_id: binary_sensor.water_pump_availability
      to: 'on'
    - platform: state
      entity_id: binary_sensor.water_tank_availability
      to: 'on'
    - platform: state
      entity_id: input_boolean.holiday_mode
      to: 'off'
    - platform: numeric_state
      entity_id: sensor.water_percentage
      below: 41
    - platform: numeric_state
      entity_id: sensor.water_well_temperature
      above: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.water_pump_availability
        state: 'on'
      - condition: state
        entity_id: binary_sensor.water_tank_availability
        state: 'on'
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.water_percentage
        below: 41
      - condition: numeric_state
        entity_id: sensor.water_well_temperature
        above: 10
  action:
    service: switch.turn_on
    entity_id: switch.water_tank_intent

# Set tank intent off when holiday mode is switched on, no matter what.
- alias: 'Switch water tank intent off when holiday mode is on no matter what'
  trigger:
    - platform: state
      entity_id: input_boolean.holiday_mode
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: 'on'
  action:
    service: switch.turn_off
    entity_id: switch.water_tank_intent

- alias: 'Send water well recovery time'
  trigger:
    platform: state
    entity_id: input_select.water_well_recover_time
  action:
    service: mqtt.publish
    data:
      topic: "water-well/recovery-time"
      payload_template: "{{ states('input_select.water_well_recover_time') }}"

- alias: 'Send water well recovery time when water pump becomes available'
  trigger:
    platform: state
    entity_id: binary_sensor.water_pump_availability
    to: 'on'
  action:
    service: mqtt.publish
    data:
      topic: "water-well/recovery-time"
      payload_template: "{{ states('input_select.water_well_recover_time') }}"

- alias: 'Send water tank sensor reading interval for when the water pump is off'
  trigger:
    platform: state
    entity_id: input_select.water_tank_level_sensor_interval_not_pumping
  action:
    service: mqtt.publish
    data:
      topic: "water-tank/interval-not-pumping"
      payload_template: "{{ states('input_select.water_tank_level_sensor_interval_not_pumping') }}"

- alias: 'Send water tank sensor reading interval for when the water pump is off just when the water tank becomes available'
  trigger:
    platform: state
    entity_id: binary_sensor.water_tank_availability
    to: 'on'
  action:
    service: mqtt.publish
    data:
      topic: "water-tank/interval-not-pumping"
      payload_template: "{{ states('input_select.water_tank_level_sensor_interval_not_pumping') }}"

## Telegram alerts
# Water level too low alert
- alias: 'Send telegram alert when water level bellow 10%'
  trigger:
    platform: numeric_state
    entity_id: sensor.water_percentage
    below: 10
  action:
    service: notify.Telegram
    data:
      message: 'Water level is now bellow 10%'
      
# Temp bellow 10 degrees pump between 81% and 95%
- alias: 'Send telegram alert when water well temperature is bellow 10 degrees'
  trigger:
    platform: numeric_state
    entity_id: sensor.water_well_temperature
    below: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: 'off'
  action:
    service: notify.Telegram
    data:
      message: 'Water well temperature is now bellow 10째C. The water pump will now pump when the water tank reaches 81% and will fill up to 95%. When the temperature goes above 10째C, the water pump will resume pumping between 41% and 95%.'

# Frost protection alert
- alias: 'Send telegram alert when water well temperature is bellow 2 degrees'
  trigger:
    platform: numeric_state
    entity_id: sensor.water_well_temperature
    below: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: 'off'
  action:
    service: notify.Telegram
    data:
      message: 'Water well temperature is now bellow 2째C. Water pump will resume working when temperature goes above 2째C.'